name: swe444
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: "^1.6.0"
  cloud_firestore: ^2.5.2
  flutter_local_notifications: ^9.0.0
  firebase_messaging: ^10.0.9
  awesome_notifications: ^0.6.13
  adobe_xd: ^2.0.0+1
  google_fonts: ^2.1.0
  flutter_screenutil: 5.0.0+2
  firebase_auth: ^3.1.1
  get: ^4.3.8
  random_string: ^2.3.1
  url_launcher: ^6.0.12
  intl: ^0.17.0

  firebase_database: ^8.0.0
  dio: ^4.0.0
  uuid: ^3.0.5
  stripe_payment: ^1.1.4
  http: ^0.13.4

  #  flutter_polyline_points: ^1.0.0
  #  google_maps: ^5.3.0
  google_maps_flutter: ^2.0.10
  provider: ^6.0.1
  #flutter_pw_validator: ^1.2.1
  cupertino_icons: ^1.0.2
  geolocator: 7.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  color: "#ededed"
  image: images/splash_screen.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #- fonts/

    - images/items.png
    - images/logo.png
    - images/money.png
    - images/events.png
    - images/splash_screen.png

  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Regular.ttf
        - asset: fonts/Tajawal-Black.ttf
        - asset: fonts/Tajawal-Bold.ttf
